# Generated by Django 4.2.9 on 2024-01-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerAuth',
            new_name='PlayerData',
        ),
    ]
